# ══════════════════════════════════════════
# Inventory — Bare Metal Servers
# ══════════════════════════════════════════

[bare_metal_servers]
mongo-node-1  ansible_host=10.0.1.10  ansible_user=ec2-user  node_role=primary
mongo-node-2  ansible_host=10.0.2.10  ansible_user=ec2-user  node_role=secondary
mongo-node-3  ansible_host=10.0.3.10  ansible_user=ec2-user  node_role=secondary

[bare_metal_servers:vars]
ansible_ssh_private_key_file=~/.ssh/mongodb-keypair.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ec2-user@<bastion-ip>'
ansible_python_interpreter=/usr/bin/python3
